name: Build release

on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install gcc-arm-linux-gnueabihf
      run: sudo apt install gcc-arm-linux-gnueabihf
    - name: Add targets
      run: rustup target add armv7-unknown-linux-gnueabihf arm-unknown-linux-gnueabihf
    - name: Build arm-unknown-linux-gnueabihf (Supports Pi 0/1)
      run: cargo build --release --target=arm-unknown-linux-gnueabihf
    - name: Build armv7-unknown-linux-gnueabihf (Supports Pi 2/3/4)
      run: cargo build --release --target=armv7-unknown-linux-gnueabihf
    - uses: ncipollo/release-action@v1
      with:
          artifacts: [
            "target/armv7-unknown-linux-gnueabihf/release/wg_display",
            "target/arm-unknown-linux-gnueabihf/release/wg_display"
          ]
          artifactErrorsFailBuild: true
          # TODO: remove me once first stable version is reached
          prerelease: true
